// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/display-protocol/dp1-feed-v2/internal/dp1svc (interfaces: ValidatorSigner)
//
// Generated by this command:
//
//	mockgen -destination=dp1svc_mock.go -package=mocks github.com/display-protocol/dp1-feed-v2/internal/dp1svc ValidatorSigner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	channels "github.com/display-protocol/dp1-go/extension/channels"
	playlist "github.com/display-protocol/dp1-go/playlist"
	playlistgroup "github.com/display-protocol/dp1-go/playlistgroup"
	gomock "go.uber.org/mock/gomock"
)

// MockValidatorSigner is a mock of ValidatorSigner interface.
type MockValidatorSigner struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorSignerMockRecorder
	isgomock struct{}
}

// MockValidatorSignerMockRecorder is the mock recorder for MockValidatorSigner.
type MockValidatorSignerMockRecorder struct {
	mock *MockValidatorSigner
}

// NewMockValidatorSigner creates a new mock instance.
func NewMockValidatorSigner(ctrl *gomock.Controller) *MockValidatorSigner {
	mock := &MockValidatorSigner{ctrl: ctrl}
	mock.recorder = &MockValidatorSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorSigner) EXPECT() *MockValidatorSignerMockRecorder {
	return m.recorder
}

// SignChannel mocks base method.
func (m *MockValidatorSigner) SignChannel(raw []byte, ts time.Time) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignChannel", raw, ts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignChannel indicates an expected call of SignChannel.
func (mr *MockValidatorSignerMockRecorder) SignChannel(raw, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignChannel", reflect.TypeOf((*MockValidatorSigner)(nil).SignChannel), raw, ts)
}

// SignPlaylist mocks base method.
func (m *MockValidatorSigner) SignPlaylist(raw []byte, ts time.Time) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignPlaylist", raw, ts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignPlaylist indicates an expected call of SignPlaylist.
func (mr *MockValidatorSignerMockRecorder) SignPlaylist(raw, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignPlaylist", reflect.TypeOf((*MockValidatorSigner)(nil).SignPlaylist), raw, ts)
}

// SignPlaylistGroup mocks base method.
func (m *MockValidatorSigner) SignPlaylistGroup(raw []byte, ts time.Time) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignPlaylistGroup", raw, ts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignPlaylistGroup indicates an expected call of SignPlaylistGroup.
func (mr *MockValidatorSignerMockRecorder) SignPlaylistGroup(raw, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignPlaylistGroup", reflect.TypeOf((*MockValidatorSigner)(nil).SignPlaylistGroup), raw, ts)
}

// ValidateChannel mocks base method.
func (m *MockValidatorSigner) ValidateChannel(raw []byte) (*channels.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateChannel", raw)
	ret0, _ := ret[0].(*channels.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateChannel indicates an expected call of ValidateChannel.
func (mr *MockValidatorSignerMockRecorder) ValidateChannel(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateChannel", reflect.TypeOf((*MockValidatorSigner)(nil).ValidateChannel), raw)
}

// ValidatePlaylist mocks base method.
func (m *MockValidatorSigner) ValidatePlaylist(raw []byte) (*playlist.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePlaylist", raw)
	ret0, _ := ret[0].(*playlist.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePlaylist indicates an expected call of ValidatePlaylist.
func (mr *MockValidatorSignerMockRecorder) ValidatePlaylist(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePlaylist", reflect.TypeOf((*MockValidatorSigner)(nil).ValidatePlaylist), raw)
}

// ValidatePlaylistGroup mocks base method.
func (m *MockValidatorSigner) ValidatePlaylistGroup(raw []byte) (*playlistgroup.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePlaylistGroup", raw)
	ret0, _ := ret[0].(*playlistgroup.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePlaylistGroup indicates an expected call of ValidatePlaylistGroup.
func (mr *MockValidatorSignerMockRecorder) ValidatePlaylistGroup(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePlaylistGroup", reflect.TypeOf((*MockValidatorSigner)(nil).ValidatePlaylistGroup), raw)
}

// ValidatePlaylistWithExtension mocks base method.
func (m *MockValidatorSigner) ValidatePlaylistWithExtension(raw []byte) (*playlist.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePlaylistWithExtension", raw)
	ret0, _ := ret[0].(*playlist.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePlaylistWithExtension indicates an expected call of ValidatePlaylistWithExtension.
func (mr *MockValidatorSignerMockRecorder) ValidatePlaylistWithExtension(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePlaylistWithExtension", reflect.TypeOf((*MockValidatorSigner)(nil).ValidatePlaylistWithExtension), raw)
}

// VerifyChannelSignatures mocks base method.
func (m *MockValidatorSigner) VerifyChannelSignatures(raw []byte) (bool, []playlist.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyChannelSignatures", raw)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]playlist.Signature)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyChannelSignatures indicates an expected call of VerifyChannelSignatures.
func (mr *MockValidatorSignerMockRecorder) VerifyChannelSignatures(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyChannelSignatures", reflect.TypeOf((*MockValidatorSigner)(nil).VerifyChannelSignatures), raw)
}

// VerifyPlaylistGroupSignatures mocks base method.
func (m *MockValidatorSigner) VerifyPlaylistGroupSignatures(raw []byte) (bool, []playlist.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPlaylistGroupSignatures", raw)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]playlist.Signature)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyPlaylistGroupSignatures indicates an expected call of VerifyPlaylistGroupSignatures.
func (mr *MockValidatorSignerMockRecorder) VerifyPlaylistGroupSignatures(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPlaylistGroupSignatures", reflect.TypeOf((*MockValidatorSigner)(nil).VerifyPlaylistGroupSignatures), raw)
}

// VerifyPlaylistSignatures mocks base method.
func (m *MockValidatorSigner) VerifyPlaylistSignatures(raw []byte) (bool, []playlist.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPlaylistSignatures", raw)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]playlist.Signature)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyPlaylistSignatures indicates an expected call of VerifyPlaylistSignatures.
func (mr *MockValidatorSignerMockRecorder) VerifyPlaylistSignatures(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPlaylistSignatures", reflect.TypeOf((*MockValidatorSigner)(nil).VerifyPlaylistSignatures), raw)
}
