// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/display-protocol/dp1-feed-v2/internal/executor (interfaces: Executor)
//
// Generated by this command:
//
//	mockgen -destination=executor_mock.go -package=mocks github.com/display-protocol/dp1-feed-v2/internal/executor Executor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	channels "github.com/display-protocol/dp1-go/extension/channels"
	playlist "github.com/display-protocol/dp1-go/playlist"
	playlistgroup "github.com/display-protocol/dp1-go/playlistgroup"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"

	models "github.com/display-protocol/dp1-feed-v2/internal/models"
	store "github.com/display-protocol/dp1-feed-v2/internal/store"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// APIInfo mocks base method.
func (m *MockExecutor) APIInfo(version string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIInfo", version)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// APIInfo indicates an expected call of APIInfo.
func (mr *MockExecutorMockRecorder) APIInfo(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIInfo", reflect.TypeOf((*MockExecutor)(nil).APIInfo), version)
}

// CreateChannel mocks base method.
func (m *MockExecutor) CreateChannel(ctx context.Context, req *models.ChannelCreateRequest) (*channels.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, req)
	ret0, _ := ret[0].(*channels.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockExecutorMockRecorder) CreateChannel(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockExecutor)(nil).CreateChannel), ctx, req)
}

// CreatePlaylist mocks base method.
func (m *MockExecutor) CreatePlaylist(ctx context.Context, req *models.PlaylistCreateRequest) (*playlist.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylist", ctx, req)
	ret0, _ := ret[0].(*playlist.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaylist indicates an expected call of CreatePlaylist.
func (mr *MockExecutorMockRecorder) CreatePlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylist", reflect.TypeOf((*MockExecutor)(nil).CreatePlaylist), ctx, req)
}

// CreatePlaylistGroup mocks base method.
func (m *MockExecutor) CreatePlaylistGroup(ctx context.Context, req *models.PlaylistGroupCreateRequest) (*playlistgroup.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylistGroup", ctx, req)
	ret0, _ := ret[0].(*playlistgroup.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaylistGroup indicates an expected call of CreatePlaylistGroup.
func (mr *MockExecutorMockRecorder) CreatePlaylistGroup(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylistGroup", reflect.TypeOf((*MockExecutor)(nil).CreatePlaylistGroup), ctx, req)
}

// DeleteChannel mocks base method.
func (m *MockExecutor) DeleteChannel(ctx context.Context, idOrSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, idOrSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockExecutorMockRecorder) DeleteChannel(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockExecutor)(nil).DeleteChannel), ctx, idOrSlug)
}

// DeletePlaylist mocks base method.
func (m *MockExecutor) DeletePlaylist(ctx context.Context, idOrSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylist", ctx, idOrSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylist indicates an expected call of DeletePlaylist.
func (mr *MockExecutorMockRecorder) DeletePlaylist(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylist", reflect.TypeOf((*MockExecutor)(nil).DeletePlaylist), ctx, idOrSlug)
}

// DeletePlaylistGroup mocks base method.
func (m *MockExecutor) DeletePlaylistGroup(ctx context.Context, idOrSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylistGroup", ctx, idOrSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylistGroup indicates an expected call of DeletePlaylistGroup.
func (mr *MockExecutorMockRecorder) DeletePlaylistGroup(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylistGroup", reflect.TypeOf((*MockExecutor)(nil).DeletePlaylistGroup), ctx, idOrSlug)
}

// GetChannel mocks base method.
func (m *MockExecutor) GetChannel(ctx context.Context, idOrSlug string) (*channels.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, idOrSlug)
	ret0, _ := ret[0].(*channels.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockExecutorMockRecorder) GetChannel(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockExecutor)(nil).GetChannel), ctx, idOrSlug)
}

// GetChannelRegistry mocks base method.
func (m *MockExecutor) GetChannelRegistry(ctx context.Context) ([]store.RegistryPublisher, []store.RegistryPublisherChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelRegistry", ctx)
	ret0, _ := ret[0].([]store.RegistryPublisher)
	ret1, _ := ret[1].([]store.RegistryPublisherChannel)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetChannelRegistry indicates an expected call of GetChannelRegistry.
func (mr *MockExecutorMockRecorder) GetChannelRegistry(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelRegistry", reflect.TypeOf((*MockExecutor)(nil).GetChannelRegistry), ctx)
}

// GetPlaylist mocks base method.
func (m *MockExecutor) GetPlaylist(ctx context.Context, idOrSlug string) (*playlist.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylist", ctx, idOrSlug)
	ret0, _ := ret[0].(*playlist.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylist indicates an expected call of GetPlaylist.
func (mr *MockExecutorMockRecorder) GetPlaylist(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylist", reflect.TypeOf((*MockExecutor)(nil).GetPlaylist), ctx, idOrSlug)
}

// GetPlaylistGroup mocks base method.
func (m *MockExecutor) GetPlaylistGroup(ctx context.Context, idOrSlug string) (*playlistgroup.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistGroup", ctx, idOrSlug)
	ret0, _ := ret[0].(*playlistgroup.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistGroup indicates an expected call of GetPlaylistGroup.
func (mr *MockExecutorMockRecorder) GetPlaylistGroup(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistGroup", reflect.TypeOf((*MockExecutor)(nil).GetPlaylistGroup), ctx, idOrSlug)
}

// GetPlaylistItem mocks base method.
func (m *MockExecutor) GetPlaylistItem(ctx context.Context, itemID uuid.UUID) (*playlist.PlaylistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistItem", ctx, itemID)
	ret0, _ := ret[0].(*playlist.PlaylistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistItem indicates an expected call of GetPlaylistItem.
func (mr *MockExecutorMockRecorder) GetPlaylistItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistItem", reflect.TypeOf((*MockExecutor)(nil).GetPlaylistItem), ctx, itemID)
}

// ListChannels mocks base method.
func (m *MockExecutor) ListChannels(ctx context.Context, limit int, cursor string, sort store.SortOrder) ([]channels.Channel, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx, limit, cursor, sort)
	ret0, _ := ret[0].([]channels.Channel)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockExecutorMockRecorder) ListChannels(ctx, limit, cursor, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockExecutor)(nil).ListChannels), ctx, limit, cursor, sort)
}

// ListPlaylistGroups mocks base method.
func (m *MockExecutor) ListPlaylistGroups(ctx context.Context, limit int, cursor string, sort store.SortOrder) ([]playlistgroup.Group, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistGroups", ctx, limit, cursor, sort)
	ret0, _ := ret[0].([]playlistgroup.Group)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPlaylistGroups indicates an expected call of ListPlaylistGroups.
func (mr *MockExecutorMockRecorder) ListPlaylistGroups(ctx, limit, cursor, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistGroups", reflect.TypeOf((*MockExecutor)(nil).ListPlaylistGroups), ctx, limit, cursor, sort)
}

// ListPlaylistItems mocks base method.
func (m *MockExecutor) ListPlaylistItems(ctx context.Context, limit int, cursor string, sort store.SortOrder, channelFilter, playlistGroupFilter string) ([]playlist.PlaylistItem, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistItems", ctx, limit, cursor, sort, channelFilter, playlistGroupFilter)
	ret0, _ := ret[0].([]playlist.PlaylistItem)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPlaylistItems indicates an expected call of ListPlaylistItems.
func (mr *MockExecutorMockRecorder) ListPlaylistItems(ctx, limit, cursor, sort, channelFilter, playlistGroupFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistItems", reflect.TypeOf((*MockExecutor)(nil).ListPlaylistItems), ctx, limit, cursor, sort, channelFilter, playlistGroupFilter)
}

// ListPlaylists mocks base method.
func (m *MockExecutor) ListPlaylists(ctx context.Context, limit int, cursor string, sort store.SortOrder) ([]playlist.Playlist, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylists", ctx, limit, cursor, sort)
	ret0, _ := ret[0].([]playlist.Playlist)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPlaylists indicates an expected call of ListPlaylists.
func (mr *MockExecutorMockRecorder) ListPlaylists(ctx, limit, cursor, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylists", reflect.TypeOf((*MockExecutor)(nil).ListPlaylists), ctx, limit, cursor, sort)
}

// ReplaceChannel mocks base method.
func (m *MockExecutor) ReplaceChannel(ctx context.Context, idOrSlug string, req *models.ChannelReplaceRequest) (*channels.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceChannel", ctx, idOrSlug, req)
	ret0, _ := ret[0].(*channels.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceChannel indicates an expected call of ReplaceChannel.
func (mr *MockExecutorMockRecorder) ReplaceChannel(ctx, idOrSlug, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceChannel", reflect.TypeOf((*MockExecutor)(nil).ReplaceChannel), ctx, idOrSlug, req)
}

// ReplaceChannelRegistry mocks base method.
func (m *MockExecutor) ReplaceChannelRegistry(ctx context.Context, req models.RegistryUpdateRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceChannelRegistry", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceChannelRegistry indicates an expected call of ReplaceChannelRegistry.
func (mr *MockExecutorMockRecorder) ReplaceChannelRegistry(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceChannelRegistry", reflect.TypeOf((*MockExecutor)(nil).ReplaceChannelRegistry), ctx, req)
}

// ReplacePlaylist mocks base method.
func (m *MockExecutor) ReplacePlaylist(ctx context.Context, idOrSlug string, req *models.PlaylistReplaceRequest) (*playlist.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePlaylist", ctx, idOrSlug, req)
	ret0, _ := ret[0].(*playlist.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplacePlaylist indicates an expected call of ReplacePlaylist.
func (mr *MockExecutorMockRecorder) ReplacePlaylist(ctx, idOrSlug, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePlaylist", reflect.TypeOf((*MockExecutor)(nil).ReplacePlaylist), ctx, idOrSlug, req)
}

// ReplacePlaylistGroup mocks base method.
func (m *MockExecutor) ReplacePlaylistGroup(ctx context.Context, idOrSlug string, req *models.PlaylistGroupReplaceRequest) (*playlistgroup.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePlaylistGroup", ctx, idOrSlug, req)
	ret0, _ := ret[0].(*playlistgroup.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplacePlaylistGroup indicates an expected call of ReplacePlaylistGroup.
func (mr *MockExecutorMockRecorder) ReplacePlaylistGroup(ctx, idOrSlug, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePlaylistGroup", reflect.TypeOf((*MockExecutor)(nil).ReplacePlaylistGroup), ctx, idOrSlug, req)
}

// UpdateChannel mocks base method.
func (m *MockExecutor) UpdateChannel(ctx context.Context, idOrSlug string, req *models.ChannelUpdateRequest) (*channels.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, idOrSlug, req)
	ret0, _ := ret[0].(*channels.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockExecutorMockRecorder) UpdateChannel(ctx, idOrSlug, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockExecutor)(nil).UpdateChannel), ctx, idOrSlug, req)
}

// UpdatePlaylist mocks base method.
func (m *MockExecutor) UpdatePlaylist(ctx context.Context, idOrSlug string, req *models.PlaylistUpdateRequest) (*playlist.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylist", ctx, idOrSlug, req)
	ret0, _ := ret[0].(*playlist.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaylist indicates an expected call of UpdatePlaylist.
func (mr *MockExecutorMockRecorder) UpdatePlaylist(ctx, idOrSlug, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylist", reflect.TypeOf((*MockExecutor)(nil).UpdatePlaylist), ctx, idOrSlug, req)
}

// UpdatePlaylistGroup mocks base method.
func (m *MockExecutor) UpdatePlaylistGroup(ctx context.Context, idOrSlug string, req *models.PlaylistGroupUpdateRequest) (*playlistgroup.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylistGroup", ctx, idOrSlug, req)
	ret0, _ := ret[0].(*playlistgroup.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaylistGroup indicates an expected call of UpdatePlaylistGroup.
func (mr *MockExecutorMockRecorder) UpdatePlaylistGroup(ctx, idOrSlug, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylistGroup", reflect.TypeOf((*MockExecutor)(nil).UpdatePlaylistGroup), ctx, idOrSlug, req)
}
