// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/display-protocol/dp1-feed-v2/internal/store (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=store_mock.go -package=mocks github.com/display-protocol/dp1-feed-v2/internal/store Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	playlist "github.com/display-protocol/dp1-go/playlist"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"

	store "github.com/display-protocol/dp1-feed-v2/internal/store"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockStore) CreateChannel(ctx context.Context, in *store.ChannelInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockStoreMockRecorder) CreateChannel(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockStore)(nil).CreateChannel), ctx, in)
}

// CreatePlaylist mocks base method.
func (m *MockStore) CreatePlaylist(ctx context.Context, id uuid.UUID, slug string, body *playlist.Playlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylist", ctx, id, slug, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePlaylist indicates an expected call of CreatePlaylist.
func (mr *MockStoreMockRecorder) CreatePlaylist(ctx, id, slug, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylist", reflect.TypeOf((*MockStore)(nil).CreatePlaylist), ctx, id, slug, body)
}

// CreatePlaylistGroup mocks base method.
func (m *MockStore) CreatePlaylistGroup(ctx context.Context, in *store.PlaylistGroupInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylistGroup", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePlaylistGroup indicates an expected call of CreatePlaylistGroup.
func (mr *MockStoreMockRecorder) CreatePlaylistGroup(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylistGroup", reflect.TypeOf((*MockStore)(nil).CreatePlaylistGroup), ctx, in)
}

// DeleteChannel mocks base method.
func (m *MockStore) DeleteChannel(ctx context.Context, idOrSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, idOrSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockStoreMockRecorder) DeleteChannel(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockStore)(nil).DeleteChannel), ctx, idOrSlug)
}

// DeletePlaylist mocks base method.
func (m *MockStore) DeletePlaylist(ctx context.Context, idOrSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylist", ctx, idOrSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylist indicates an expected call of DeletePlaylist.
func (mr *MockStoreMockRecorder) DeletePlaylist(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylist", reflect.TypeOf((*MockStore)(nil).DeletePlaylist), ctx, idOrSlug)
}

// DeletePlaylistGroup mocks base method.
func (m *MockStore) DeletePlaylistGroup(ctx context.Context, idOrSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylistGroup", ctx, idOrSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylistGroup indicates an expected call of DeletePlaylistGroup.
func (mr *MockStoreMockRecorder) DeletePlaylistGroup(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylistGroup", reflect.TypeOf((*MockStore)(nil).DeletePlaylistGroup), ctx, idOrSlug)
}

// GetChannel mocks base method.
func (m *MockStore) GetChannel(ctx context.Context, idOrSlug string) (*store.ChannelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, idOrSlug)
	ret0, _ := ret[0].(*store.ChannelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockStoreMockRecorder) GetChannel(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockStore)(nil).GetChannel), ctx, idOrSlug)
}

// GetChannelRegistry mocks base method.
func (m *MockStore) GetChannelRegistry(ctx context.Context) ([]store.RegistryPublisher, []store.RegistryPublisherChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelRegistry", ctx)
	ret0, _ := ret[0].([]store.RegistryPublisher)
	ret1, _ := ret[1].([]store.RegistryPublisherChannel)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetChannelRegistry indicates an expected call of GetChannelRegistry.
func (mr *MockStoreMockRecorder) GetChannelRegistry(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelRegistry", reflect.TypeOf((*MockStore)(nil).GetChannelRegistry), ctx)
}

// GetPlaylist mocks base method.
func (m *MockStore) GetPlaylist(ctx context.Context, idOrSlug string) (*store.PlaylistRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylist", ctx, idOrSlug)
	ret0, _ := ret[0].(*store.PlaylistRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylist indicates an expected call of GetPlaylist.
func (mr *MockStoreMockRecorder) GetPlaylist(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylist", reflect.TypeOf((*MockStore)(nil).GetPlaylist), ctx, idOrSlug)
}

// GetPlaylistGroup mocks base method.
func (m *MockStore) GetPlaylistGroup(ctx context.Context, idOrSlug string) (*store.PlaylistGroupRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistGroup", ctx, idOrSlug)
	ret0, _ := ret[0].(*store.PlaylistGroupRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistGroup indicates an expected call of GetPlaylistGroup.
func (mr *MockStoreMockRecorder) GetPlaylistGroup(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistGroup", reflect.TypeOf((*MockStore)(nil).GetPlaylistGroup), ctx, idOrSlug)
}

// GetPlaylistItem mocks base method.
func (m *MockStore) GetPlaylistItem(ctx context.Context, itemID uuid.UUID) (*store.PlaylistItemRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistItem", ctx, itemID)
	ret0, _ := ret[0].(*store.PlaylistItemRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistItem indicates an expected call of GetPlaylistItem.
func (mr *MockStoreMockRecorder) GetPlaylistItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistItem", reflect.TypeOf((*MockStore)(nil).GetPlaylistItem), ctx, itemID)
}

// GetPlaylistItems mocks base method.
func (m *MockStore) GetPlaylistItems(ctx context.Context, idOrSlug string) ([]store.PlaylistItemRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistItems", ctx, idOrSlug)
	ret0, _ := ret[0].([]store.PlaylistItemRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistItems indicates an expected call of GetPlaylistItems.
func (mr *MockStoreMockRecorder) GetPlaylistItems(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistItems", reflect.TypeOf((*MockStore)(nil).GetPlaylistItems), ctx, idOrSlug)
}

// ListChannels mocks base method.
func (m *MockStore) ListChannels(ctx context.Context, p *store.ListPlaylistsParams) ([]store.ChannelRecord, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx, p)
	ret0, _ := ret[0].([]store.ChannelRecord)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockStoreMockRecorder) ListChannels(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockStore)(nil).ListChannels), ctx, p)
}

// ListPlaylistGroups mocks base method.
func (m *MockStore) ListPlaylistGroups(ctx context.Context, p *store.ListPlaylistsParams) ([]store.PlaylistGroupRecord, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistGroups", ctx, p)
	ret0, _ := ret[0].([]store.PlaylistGroupRecord)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPlaylistGroups indicates an expected call of ListPlaylistGroups.
func (mr *MockStoreMockRecorder) ListPlaylistGroups(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistGroups", reflect.TypeOf((*MockStore)(nil).ListPlaylistGroups), ctx, p)
}

// ListPlaylistItems mocks base method.
func (m *MockStore) ListPlaylistItems(ctx context.Context, p *store.ListPlaylistItemsParams) ([]store.PlaylistItemRecord, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistItems", ctx, p)
	ret0, _ := ret[0].([]store.PlaylistItemRecord)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPlaylistItems indicates an expected call of ListPlaylistItems.
func (mr *MockStoreMockRecorder) ListPlaylistItems(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistItems", reflect.TypeOf((*MockStore)(nil).ListPlaylistItems), ctx, p)
}

// ListPlaylists mocks base method.
func (m *MockStore) ListPlaylists(ctx context.Context, p *store.ListPlaylistsParams) ([]store.PlaylistRecord, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylists", ctx, p)
	ret0, _ := ret[0].([]store.PlaylistRecord)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPlaylists indicates an expected call of ListPlaylists.
func (mr *MockStoreMockRecorder) ListPlaylists(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylists", reflect.TypeOf((*MockStore)(nil).ListPlaylists), ctx, p)
}

// ListPlaylistsInChannel mocks base method.
func (m *MockStore) ListPlaylistsInChannel(ctx context.Context, idOrSlug string) ([]store.PlaylistRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistsInChannel", ctx, idOrSlug)
	ret0, _ := ret[0].([]store.PlaylistRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlaylistsInChannel indicates an expected call of ListPlaylistsInChannel.
func (mr *MockStoreMockRecorder) ListPlaylistsInChannel(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistsInChannel", reflect.TypeOf((*MockStore)(nil).ListPlaylistsInChannel), ctx, idOrSlug)
}

// ListChannelsForPlaylist mocks base method.
func (m *MockStore) ListChannelsForPlaylist(ctx context.Context, idOrSlug string) ([]store.ChannelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannelsForPlaylist", ctx, idOrSlug)
	ret0, _ := ret[0].([]store.ChannelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannelsForPlaylist indicates an expected call of ListChannelsForPlaylist.
func (mr *MockStoreMockRecorder) ListChannelsForPlaylist(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannelsForPlaylist", reflect.TypeOf((*MockStore)(nil).ListChannelsForPlaylist), ctx, idOrSlug)
}

// ListPlaylistsInGroup mocks base method.
func (m *MockStore) ListPlaylistsInGroup(ctx context.Context, idOrSlug string) ([]store.PlaylistRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistsInGroup", ctx, idOrSlug)
	ret0, _ := ret[0].([]store.PlaylistRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlaylistsInGroup indicates an expected call of ListPlaylistsInGroup.
func (mr *MockStoreMockRecorder) ListPlaylistsInGroup(ctx, idOrSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistsInGroup", reflect.TypeOf((*MockStore)(nil).ListPlaylistsInGroup), ctx, idOrSlug)
}

// Ping mocks base method.
func (m *MockStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoreMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStore)(nil).Ping), ctx)
}

// ReplaceChannelRegistry mocks base method.
func (m *MockStore) ReplaceChannelRegistry(ctx context.Context, publishers []store.RegistryPublisher, channels []store.RegistryPublisherChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceChannelRegistry", ctx, publishers, channels)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceChannelRegistry indicates an expected call of ReplaceChannelRegistry.
func (mr *MockStoreMockRecorder) ReplaceChannelRegistry(ctx, publishers, channels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceChannelRegistry", reflect.TypeOf((*MockStore)(nil).ReplaceChannelRegistry), ctx, publishers, channels)
}

// UpdateChannel mocks base method.
func (m *MockStore) UpdateChannel(ctx context.Context, idOrSlug string, in *store.ChannelInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, idOrSlug, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockStoreMockRecorder) UpdateChannel(ctx, idOrSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockStore)(nil).UpdateChannel), ctx, idOrSlug, in)
}

// UpdatePlaylist mocks base method.
func (m *MockStore) UpdatePlaylist(ctx context.Context, idOrSlug string, body *playlist.Playlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylist", ctx, idOrSlug, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlaylist indicates an expected call of UpdatePlaylist.
func (mr *MockStoreMockRecorder) UpdatePlaylist(ctx, idOrSlug, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylist", reflect.TypeOf((*MockStore)(nil).UpdatePlaylist), ctx, idOrSlug, body)
}

// UpdatePlaylistGroup mocks base method.
func (m *MockStore) UpdatePlaylistGroup(ctx context.Context, idOrSlug string, in *store.PlaylistGroupInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylistGroup", ctx, idOrSlug, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlaylistGroup indicates an expected call of UpdatePlaylistGroup.
func (mr *MockStoreMockRecorder) UpdatePlaylistGroup(ctx, idOrSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylistGroup", reflect.TypeOf((*MockStore)(nil).UpdatePlaylistGroup), ctx, idOrSlug, in)
}
